### ISSUE TITLE
Simplify everything (refactor)

### ISSUE THREAD

**Issue by tarsoly** [ABC-iRobotics/mxw-robot#1]
- [x] Separate robot model and control board (panel) into different components
- [x] The robot base position and orientation must be adjustable from config
- [x] Geometric transformation should be reviewed
- [x] Built-in interpolation methods should be applied if possible
- [x] Thorough code cleanup

**Comment by fletli** [comment]
Done with https://github.com/ABC-iRobotics/mxw-robot/commit/bac66972cb22aba069e5afd214a09690141059e7
